### PR TITLE
Add __future__.division imports, update tests

### PR DESCRIPTION
**Pull request by shadowwalkersb**

### CODE REVIEW

**Comment by shadowwalkersb** [comment]
@sludtke42 , any comments here? Unnecessary?

**Comment by sludtke42** [comment]
Did you reply to my question about just keeping all three variants of __div__ for the time being?  I think that solves the problem for now without adding all of the future import divs?  As far as I understand, defining all 3 is not harmful, and should be ok with the other ->py3 changes you've made?


--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu <mailto:sludtke@bcm.edu>>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem <http://www.bcm.edu/biochem>)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu <http://cryoem.bcm.edu/>)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr <http://www.bcm.edu/research/cibr>)
Co-Director National Center For Macromolecular Imaging                  (ncmi.bcm.edu <http://ncmi.bcm.edu/>)

**Comment by shadowwalkersb** [comment]
@mstabrin added `__div__` binding in #230 . That handles sparx's code still using py2 divisions. 

Changes here are for eman2, since eman2 now uses py3 division. With the existence of both py2/3 bindings in boost, I think the changes here are even more important. As a simple example, you can try `6/2` in e2.py with and without the changes here. My understanding is that we want `__future__.division` in `e2.py` and/or `e2_real.py`. We don't want our divisions to use `__div__`, we want `__truediv__`. I think, this is the right way to fix `e2.py`. But, I am trying to convince myself that all files need to have `__future__.division` imported to make sure py3 divisions are used in eman2 code, be it pure python divisions or boost divisions.

**Comment by sludtke42** [comment]
It should be pretty trivial to insert a test into a couple of the e2* or sx* programs at the beginning, then running them in the normal way to insure that division is working as expected?

--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu <mailto:sludtke@bcm.edu>>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem <http://www.bcm.edu/biochem>)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu <http://cryoem.bcm.edu/>)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr <http://www.bcm.edu/research/cibr>)
Co-Director National Center For Macromolecular Imaging                  (ncmi.bcm.edu <http://ncmi.bcm.edu/>)

**Comment by shadowwalkersb** [comment]
> It should be pretty trivial to insert a test into a couple of the e2* or sx* programs at the beginning, then running them in the normal way to insure that division is working as expected?

Not following.

This PR adds the missing imports to files that currently do not have any divisions, thus the tool did not add any imports. The idea of adding the imports anyways is to make sure in case division is added in the future to those files or new files are added, to make sure they have the expected imports, because we tend to forget about them. From this point on we can't run the py3 fixing tools for division, because we already started fixing them manually. Running the tools will overwrite them. So, this PR is to make sure all files are use py3-division.

**Comment by sludtke42** [comment]
Ok, as long as Markus has no problems with this, I'm fine as well

--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu <mailto:sludtke@bcm.edu>>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem <http://www.bcm.edu/biochem>)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu <http://cryoem.bcm.edu/>)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr <http://www.bcm.edu/research/cibr>)
Co-Director National Center For Macromolecular Imaging                  (ncmi.bcm.edu <http://ncmi.bcm.edu/>)

**Comment by shadowwalkersb** [comment]
@mstabrin , does this look OK to you?

**Pull request merged**
