### PR TITLE
PyQt4 signal fixes

### LINKED ISSUE #212: Bug: emimage2d
**Steps to reproduce:**

1. `python -m eman2_gui.emimage2d`
1. `Shift` + scroll mouse wheel

```
Traceback (most recent call last):
  File "/miniconda/lib/python2.7/site-packages/eman2_gui/emimage2d.py", line 1748, in wheelEvent
    self.mousewheel.emit(event)
TypeError: EMImage2DWidget.mousewheel[QMouseEvent].emit(): argument 1 has unexpected type 'QWheelEvent'
```

### PR DESCRIPTION
**Pull request by shadowwalkersb**
Cleaning up signals that look like are not used anywhere and a connection to an empty function.

Also, should resolve problems like this.

```
$ Traceback (most recent call last):
  File "/minicondas/lib/python2.7/site-packages/eman2_gui/emplot2d.py", line 815, in mousePressEvent
    self.update_selected((event.x(),event.y()),lc)
  File "/minicondas/lib/python2.7/site-packages/eman2_gui/emplot2d.py", line 799, in update_selected
    self.selected.emit(self.selected)
AttributeError: 'list' object has no attribute 'emit'
```

32b84e5699323353c5434cf18b194e0b217719dd fixes #212 .

### CODE REVIEW

**Comment by shadowwalkersb** [comment]
The signals removed here were causing crashes. Gladly would revert the changes, but how do you suggest we fix them, then?

Another thing that's removed is a connection to an empty function (edited the description above). Should that be reverted as well?

**Comment by sludtke42** [comment]
I'm traveling thru friday and cannot do a lot, but it looks like the emit lines in this change should never have worked?  I mean, nothing in Qt4 would have given a list object emit() capabilities. Normally it would be the widget itself which would be emitting signals.  That is, I don't quite understand how, if you didn't change anything in this code, it suddenly doesn't work...
--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu <mailto:sludtke@bcm.edu>>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem <http://www.bcm.edu/biochem>)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu <http://cryoem.bcm.edu/>)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr <http://www.bcm.edu/research/cibr>)
Co-Director National Center For Macromolecular Imaging                  (ncmi.bcm.edu <http://ncmi.bcm.edu/>)

**Comment by shadowwalkersb** [comment]
So, this is what happened to `emit` when transitioned from old style signal and slots to new style.

https://github.com/cryoem/eman2/commit/82e4aa14d943c4480f9fb933e8283e7c56816c35#diff-091825a864850e8ec2d055c59dc5953bL794
`self.emit(QtCore.SIGNAL("selected"),self.selected)` -> `self.selected.emit(self.selected)`

What previously was a string passed to `QtCore.SIGNAL()` became a class member and clashed with already existing `self.select`. Did it work before the change? Dunno. Maybe, it worked before, because `emit()` was passed a signal with a string passed to it and some data. So, no room for name clashing. Or, maybe, it didn't work, but the old style `emit()` didn't complain.

If we want to keep the signals, I think we could rename either the signal or the field. Which one would you prefer?

**Comment by shadowwalkersb** [comment]
I pushed a few more changes involving missing imports and renaming functions.

**Comment by shadowwalkersb** [comment]
So much for branching...

**Pull request merged**
