### PR TITLE
Python3 divisions

### PR DESCRIPTION
**Pull request by shadowwalkersb**
First commit in this PR is the result of running the automated tool to change divisions. Unfortunately, the tool works for expressions containing only a single division and no other operations. The third commit adds a file with the list of such missed expressions. We need to update those expressions manually. Here is the file format.
```
filename:line <expression-containing-divisions> |  <expression-containing-divisions>
```
Note the duplication of `<expression-containing-divisions>`. I thought it would be easier to edit the second expression instead of copy-pasting the whole thing for every line. My proposed workflow is,
1. If **any** of the inputs of the division are **floats**, **delete** the whole line. No need to change.
1. If **both** of the inputs of the division are **integers**, update the division. `a/b` -> `old_div(a,b)`
1. Commit and push your changes to **this** branch, `py3-div`.

Once this file is updated, we can read the file and use the first expression as reference and update it with the second expression in the updated file.

Any suggestions to make this process easier are welcome.

### CODE REVIEW

**Comment by shadowwalkersb** [comment]
OK, I think, I need some feedback to make sure what I am trying to do here is correct. The following is my understanding of the division problem occurring in the transition from Python 2 to Python 3. The difference between the two versions is in how division (`/`) is treated when **both** of the inputs to a division operation are **integers**. Python 2 performs **integer division**, Python 3 performs **float division** (**floating point division** could be the official term). If **any** of the inputs is **float**, both versions treat it as a **float** division. If the division operator is `//`, then the operation is **integer** division regardless of the input types. To solve this problem, the conversion package used here wraps the divisions with `old_div()`, http://python-future.org/compatible_idioms.html#division. However, it seems to work only on expressions containing single divisions which is why we have to do some manual updates. Based on all this, here is the workflow I have followed so far. I tried to make the commits reasonably small and to contain the same type of changes to make it easier to review.

1. https://github.com/cryoem/eman2/pull/217/commits/34a5aaeeac9ae422cb137d012627c5f9e7afd267 : Run the automated tool. All isolated divisions, `a/b` should have been replaced with `old_div(a/b)`.
1. https://github.com/cryoem/eman2/pull/217/commits/d4973670fb11eddfb35f7062c1094938b0002202 : List all non-isolated divisions that the automated tool missed. The file is `py3_divs.txt`.
1. https://github.com/cryoem/eman2/pull/217/commits/ae84a4a8da47591eef1346bfb2076e093a2bf164 : Add a script to read `py3_divs.txt` and replace the string in the second column with the third column. Now, all we need to do is update `py3_divs.txt`.
1. Commits with messages like `remove float divisions <some-number>` or `remove integer divisions <some-number>` : Any division that has at least one float as input or any integer division (`//`) is treated the same by Python 2/3, so there is no need to change those expressions. Thus, simply remove lines that have `float(a)/b`, `a/float(b)`, `xx.x/y`, `xx/yy.y` or `a//b` from `py3_divs.txt`. These should be mostly easy to review.
1. https://github.com/cryoem/eman2/pull/217/commits/317114ed2527a03c9e5959cad7bc7f935b14fec2 : **This one may need more attention.** I assumed that `math.pi`, `math.cos` and similar, `np.pi` type of constants or returned values are floats. So, remove them.
1. https://github.com/cryoem/eman2/pull/217/commits/dad9b16522c5ea9ed9da155a2fb5571aca2e21e4 : **This one may need more attention.** These are multiple input expressions which have a float somewhere  that eventually leads to a float input for the division operation. So, remove them.
1. Upcoming changes will have manually wrapped expressions in the third column. I will use the script in https://github.com/cryoem/eman2/pull/217/commits/535843470bf01078a4ce752c05e9f339188bcbb4 which I can run in my IDE on selected texts and it copies the changed code to the clipboard which I can simply paste in the IDE. In case anybody finds it useful for updating SPARX/SPHIRE.
1. When we have a final updated `py3_divs.txt`, we will just need to run the script that updates all the python files.

So, does this seem to be a reasonable way to move forward?

**Comment by shadowwalkersb** [comment]
Sorry for the poor wording.
Isolated divisions are single divisions with no other operations in an expression, `a/b`, vs non-isolated divisions like `a+b/c`, `a*b/c` and so on. The conversion tool parses `a/b` and ends up with three children, ['a', '/', 'c'] and checks if child[1] == '/'. With what I called non-isolated divisions, child[1] is not '/', so the tool skips more complicated expressions involving a division somewhere in it.

If you just reply to the emails sent by GitHub, they should be posted here. Alternatively, you could follow the link at the bottom of the email that reads something like 'view it on GitHub'.

**Comment by shadowwalkersb** [comment]
The code has been updated with all the proposed changes, except sparx. Ready to review, either the listings or the source code.

**Comment by shadowwalkersb** [comment]
This is ready to merge, if no objections. I think we should merge this, before any more merge conflicts. Manual editing is quite energy consuming. It should be OK to continue with sparx updates later.

**Comment by shadowwalkersb** [comment]
If I remember correctly, there are more than **6000** divisions. Even, **600** changes scares people. So, eventually, making every division `//` or `/` would take quite some time.  Because, the tools I have found so far target Py2 and Py3 compatibility at the same time, and do not offer changing the divisions to `//` and `/`. The goal of this stage is the same as the previous stages, to make the code run on both Py2 and Py3, so we can continue with Python 2 until we are completely ready to switch to Python 3. And after the complete transition, if anyone is willing to go through all 6000 divisions and get rid of `old_div`s... certainly, would be welcome.

**Comment by sludtke42** [comment]
I have only two concerns:
1) old_div is MUCH harder to read, and manually converting it back to a "/" or a "//" is much harder than converting a "/" to a "//" if necessary
2) replacing a bultin division with a function call may have a speed impact?

--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu <mailto:sludtke@bcm.edu>>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem <http://www.bcm.edu/biochem>)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu <http://cryoem.bcm.edu/>)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr <http://www.bcm.edu/research/cibr>)
Co-Director National Center For Macromolecular Imaging                  (ncmi.bcm.edu <http://ncmi.bcm.edu/>)

**Comment by shadowwalkersb** [comment]
1. As far as I can tell `//`s are not replaced with `old_div`, `//` behaves the same in Py2/3.
1. Speed impact, well, I don't see any other options. I am open to alternatives, though.

**Comment by shadowwalkersb** [comment]
The merge conflict resolution seems to have brought this new file, `examples/alignertest_rt2d3dtree.py`, from `master`. It might me a good idea to check for divisions.

**Pull request merged**
