### PR TITLE
unset CFLAGS, which somehow produces faster fftw3 binaries, ¯\_(ツ)_/¯ [ci skip]

### PR DESCRIPTION
**Pull request by shadowwalkersb**

### CODE REVIEW

**Comment by shadowwalkersb** [comment]
This has been tested on Mac OSX, Ubuntu 16 VM and a cluster with CentOS6. This change alone has improved e2speedtest results by 30-60%. More tests are welcome, but I am inclined to merge it. The updated fftw binaries are already available on cryoem channel.

**Comment by pawelpap9** [comment]
Hi

So how one would do the test?  Is it in source, binary or both?

Is it in master or some other branch?

Regards,
Pawel

**Comment by shadowwalkersb** [comment]
It is in master, but this change is in a script that is used for pydusa installation on clusters. So, it doesn't do anything for source installations. But, the same changes have been applied to the fftw binaries we host on our anaconda channel, cryoem. To pull that you need to update your fftw binary.

`conda update fftw-mpi -c cryoem`

This should update to `fftw-mpi 3.3.6-1`.

I haven't checked if daily binaries have been updated properly.

**Comment by pawelpap9** [comment]
Thanks, I'll try tomorrow. 

Regards,
Pawel

**Pull request merged**
