### PR TITLE
Create sxmask

### PR DESCRIPTION
**Pull request by mstabrin**

### CODE REVIEW

**Comment by pawelpap9** [comment]
While the speed is always good, there are two issues I cannot get from the code easily:

it should work exactly as the previous version, at least for parameters I put there as default. As explained earlier, any change will result in change of results of refinement.

When you add new commands such as sxmask it is extremely important that the functions wrapped are also accessible during interactive sessions. Otherwise it is very difficult to test anything. In other words, sx programs should be just wrappers for various functions. This is of course true only for simple commands. Nobody epects ro run meridien interactively.
As far as I can tell from the code, this is how you put it, so this is just a reminder.

**Comment by mstabrin** [comment]
Hello Pawel,   
Thank you for pointing out that real does not say anything here.  
I, of course, mean exact, since I do not sample the cosine in advance and therefore can use floating point values instead of integers.  
Best,  
Markus

**Comment by pawelpap9** [comment]
So are you saying that in some other code only integer values of cosine are used?  There would be only three of them: -1, 0, and 1.
Where does it happen?

**Comment by mstabrin** [comment]
No, I mean that the values of the cosine are sampled in advance in a lookup table and the edge distance is rounded to the next integer index inside of the lookup table.

**Comment by mstabrin** [comment]
The lookup table is created here:  
https://github.com/cryoem/eman2/blob/master/libEM/sparx/util_sparx.cpp#L30479

And the assignment happens here:  
https://github.com/cryoem/eman2/blob/master/libEM/sparx/util_sparx.cpp#L30515

**Comment by pawelpap9** [comment]
I am not sure you realize that functional tabularization is a standard practice in numerical applications and it is not any less "exact" that laborious calculation of function values within nested loops?

Please remove "exact" term, there is nothing exact about it.
If you are worried about it, evaluate numerical accuracy of tabularization.  If you think it is insufficient and actually makes a difference, chose table length that would satisfy your high standards.

**Pull request merged**
