### PR TITLE
Fix indentations as preparation for Python 3 transition

### PR DESCRIPTION
**Pull request by shadowwalkersb**
These are trivial whitespace changes. Due to the massive changes involved, it gets more challenging to keep them on a separate branch as development on 'master' continues. More development brings more merge conflicts.

Print statements have been changed to Python3 style. Without them the tools fail. It is not trivial to remove them after all the whitespace changes either. So, instead of removing them, print statements have been made Python 2 and 3 compatible.

### CODE REVIEW

**Comment by g5v991x** [comment]
I am still doing some test on e2boxer.. Maybe later today? Or shall I fix this first before committing new changes?

**Comment by shadowwalkersb** [comment]
Either way. As long as the conflicts are fixed.

**Comment by g5v991x** [comment]
I solved the conflicts. I am not quite sure what is changed in 'fix_indentations' but the indentation in merged version looks okay to me

**Comment by shadowwalkersb** [comment]
👍 Github is happy! Thanks!

**Comment by shadowwalkersb** [comment]
They will have to be handled manually, then.

**Comment by shadowwalkersb** [comment]
> print "abc","def" -> print("abc","def") is not ok at all.

How is it supposed to be handled?

**Comment by sludtke42** [comment]
I don't know how to handle it pre-transition. There are several important sorts of formatting things which won't work this way. Consider something as simple as :

>>> print("abc","\t","def")
('abc', '\t', 'def')

>>> print "abc","\t","def"
abc 	def

There are also many cases of 

print "\r status {}/{}     ".format(a,b),
sys.stdout.flush()

which is used to update progress on the screen without creating many new lines. While there is an equivalent for Python3, it is not backwards compatible at all.

--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D.
Charles C. Bell, Jr. Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr)
Co-Director National Center For Macromolecular Imaging                  (ncmi.bcm.edu)
Baylor College of Medicine                             
sludtke@bcm.edu

**Comment by pawelpap9** [comment]
In [1]: print  "abc","def"abc def
In [2]: from __future__ import print_function
In [3]: print("abc","def")abc def

**Comment by pawelpap9** [comment]
In [4]: print("abc","\t","def")abc   def

**Comment by shadowwalkersb** [comment]
Actually, is there any sample output that shows that this is not really working?

**Comment by shadowwalkersb** [comment]
I mean, output from real eman code on this branch.

**Comment by shadowwalkersb** [comment]
Tests for Linux and Windows have passed. TravisCI will likely take a while. So, will be merging this soon. Once this is merged into 'master', print statements in Python will have to comply with Python 3 standards, I think. The concerns mentioned above were, actually, implemented in the initial state of this PR. Specifically, see here, https://github.com/cryoem/eman2/pull/132/commits/82845541baf04db8d60ee55d52f5cf5a48d7e934.

**Comment by sludtke42** [comment]
Ok, didn’t see that when skimming through the patch.

**Comment by shadowwalkersb** [comment]
So, shall we merge or wait for TravisCI? Backlogs might clear overnight and hopefully we won't get any merge conflicts till tomorrow?

**Comment by sludtke42** [comment]
It's fine, go ahead.
--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D.
Charles C. Bell, Jr. Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr)
Co-Director National Center For Macromolecular Imaging                  (ncmi.bcm.edu)
Baylor College of Medicine                             
sludtke@bcm.edu

**Pull request merged**
