### PR TITLE
Restore broken images

### PR DESCRIPTION
**Pull request by shadowwalkersb**

### CODE REVIEW

**Comment by shadowwalkersb** [comment]
This is what I get before restoration when I try to view the files.

screen shot 2017-11-07 at 5 18 57 pm

Not sure if images in folder `macimages` are, actually, meant for Mac OSX. And looking through where images are used, I see references to both `/images` and `images/macimages`.

**Comment by sludtke42** [comment]
Hmm. Maybe I misunderstood what they are. I think there are some images which were used as icons when EMAN2 was installed in /applications. Given the current strategy, those images may actually be obsolete...

--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D.
Charles C. Bell, Jr. Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr)
Co-Director National Center For Macromolecular Imaging                  (ncmi.bcm.edu)
Baylor College of Medicine                             
sludtke@bcm.edu

**Comment by shadowwalkersb** [comment]
Force-pushed a commit that reverts the commit, ccf6ffb244cc6a35342e517f7ad393d6f81386f6, which seems to have broken the images.

**Comment by shadowwalkersb** [comment]
After looking which images are used, it looks like there is no need to restore any broken images. Some refactoring is done in PR #141 , so this is redundant. Will be closing this.

**Pull request closed without merging**
