### PR TITLE
Catch value error in file content

### PR DESCRIPTION
**Pull request by mstabrin**
e2display.py is crashing when the file contains a timestring like:

slurmstepd: error: *** JOB 156628 ON en041 CANCELLED AT 2020-09-22T19:09:46 ***

### CODE REVIEW

**Comment by g5v991x** [comment]
probably better to fix the re we use for float searching... but I am not good at re so it will probably take some time. right now try/except wont hurt...

**Comment by mstabrin** [comment]
Any more thoughts about it? :)

**Comment by mstabrin** [comment]
@shadowwalkersb @sludtke42 @g5v991x I made some adjustments to the regular expression and tried to fix some followup problems. Could you check if you like it?

**Comment by g5v991x** [comment]
it looks great. but again I am bad at regrex so you probably shouldn't take my word for it... I would just go ahead and merge this into master. I will complain if I run into any additional bugs..

**Review by shadowwalkersb — APPROVED** [review]
Looks good to me.

**Comment by g5v991x** [comment]
Is this causing the broken fsc plot in e2display browser in the current version?

**Comment by sludtke42** [comment]
What problem are you referring to?  I can display FSC curves correctly.

**Comment by g5v991x** [comment]
I have display issues on two machines now...

**Comment by sludtke42** [comment]
Can you be more specific? I am on master with an update yesterday and I was able to display FSC curves in both SPT and SPA workflows.

**Comment by mstabrin** [comment]
If you think the problem is due to my adjusted regex I can check it if you provide an example FSC file :)

**Comment by g5v991x** [comment]
It seems that for all text files it does not read the first column... I triggered it again on a mac with clean installation. Since nobody reproduces this, I will look into this myself first...

**Comment by sludtke42** [comment]
I did see that happen once, maybe last week, and I thought I'd fixed something to stop the problem. I don't see the problem now, and there are no diffs between my version and master, so I'm not sure what's going on...

**Comment by g5v991x** [comment]
So the issue is the regex you use does not catch the first number at the beginning of a file.
If you just open the regex example page you gave https://regex101.com/r/68zUsE/4/, and add any number at the beginning of the file, it will fail to recognize. I can fix it on my side by simply padding an empty line when reading any file, but it would be better to fix the regex somehow...

**Comment by mstabrin** [comment]
I am on it :)

**Comment by mstabrin** [comment]
Filed a new pull request #505

**Pull request merged**
