### PR TITLE
added normalized output volume

### PR DESCRIPTION
**Pull request by taputechnic**
The PostRefiner now solicits the mask threshold in units of sigma. I normalized the volume so that the threshold you find in Chimera corresponds to the PostRefiner threshold.

### CODE REVIEW

**Comment by pawelpap9** [comment]
Please remove these changes.  It is a very bad idea to change volume normalization as it breaks other commands that depend on the assumption the normalization is correct, i.e., agrees with the data.  In addition, there is no need to write additional volumes to the already excessive output of meridien which already takes huge disk space.
If you need it, please put it to postrefiner, where it belongs.  You will not need to clutter the disk with volumes that are rarely used.

**Comment by mstabrin** [comment]
Hello Pawel,

this changed happened in response to the change of the mask threshold change in the PostRefiner: https://github.com/cryoem/eman2/commit/d7eb986ec9606c283cbc90bee4182ae6e7696cb6

Since the change was coming from your lab, we thought you want to go in this direction and in terms of automation, this makes actually a lot of sense.  
However, the user needs to have a volume to check the threshold in chimera, so we decided to add just one small output file to meridien instead of introducing a whole new command that needs to have a separate step in the GUI.
This also means, that this normalized volume is used every time before post refining, so rarely used is not quite correct.

We will work on a way to cleanup the directories after an successful run.

best,
Markus

**Comment by pawelpap9** [comment]
I never suggested making changes in meridien.
Do not introduce trivial functions into complicated code.  It should never be done this way.  The operation you have in mind is trivial.  Put it elsewhere.
Generally, please do not make ANY changes in meridien code without checking first.  The code is somewhat fragile and the less you change it the better.

**Comment by pawelpap9** [comment]
There must have been a miscommunication.  Zhong added it into postrefiner based on your group request.  Or maybe it even somebody from your side.  If it bother you, just remove it from there.
If you cannot put volume normalization in a sensible place outside of meridien, the best solution is to add the change to chimera.  I have good relations with them and they are receptive o suggestions that help users.  They should also recognize the fact that at least what happens to me is that input volume has very low amplitudes (say 1.e-7), which breaks chimera.  So it would make good sense to add there optional normalization.

**Comment by taputechnic** [comment]
On 10/2/18 7:29 PM, Pawel wrote:
>
> There must have been a miscommunication. Zhong added it into 
> postrefiner based on your group request. Or maybe it even somebody 
> from your side. If it bother you, just remove it from there.
>
If we can restore the old PostRefiner behavior, I'm fine with undoing my 
changes to Meridien.  I found the PostRefiner change to be rather 
confusing, but I assumed it was put there for a reason. Adding the 
normalized volume was simply a workaround for the users' benefit.

**Comment by mstabrin** [comment]
Hello Pawel,

I see, I will start an investigation.  
Personally, I do like the idea of using sigma as it could be generalized, but for the user it is quite painful right now.

We will not make any changes to meridien right now, but first try to come up with a better solution.

best,
Markus

**Comment by pawelpap9** [comment]
I am virtually certain we did not initialize the change in postrefiner.  I remember conversation about it, it might have been spearheaded by Christos.
Whatever the case is, it is trivial to change it back.  I assume you can handle it as Zhong no longer works on the project.

**Comment by gatsogia** [comment]
I was very surprised by that change, in general it is a good idea, but not as long people simply copy paste threshold values
from Chimera's volume viewer...


Von meinem Samsung Galaxy Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: Pawel <notifications@github.com>
Datum: 02.10.18 19:42 (GMT+01:00)
An: cryoem/eman2 <eman2@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [cryoem/eman2] added normalized output volume (#256)


I am virtually certain we did not initialize the change in postrefiner. I remember conversation about it, it might have been spearheaded by Christos.
Whatever the case is, it is trivial to change it back. I assume you can handle it as Zhong no longer works on the project.

-

**Comment by pawelpap9** [comment]
I gave this issue some thought and I realized this is all based on misunderstanding how the system works.

Meridien applies internal normalization of the 2D input data and computed structures correspond to this normalization.

It follows that all structures produced by meridien have the same normalization.  It is true only approximately, as it depends on filtration, but it is within few percent as far as I remember.  You can double check it by checking normalization of structures from different project.

What you initially put there was strange, as as far as I remember you used normalization over the entire volume, which is incorrect as then obviously normalization of the structure would depend on the size of the volume.  Meridien normalization is within the mask (roughly).

The proper normalization of meridien structure (proper meaning related to 2D data) is used in other places, in particular in signal subtraction protocol.

What follows from it is please do not ever change normalization of meridien structures as it will have unintended consequences.  Most likely it will confuse users as certain things (like masks) have to be expressed in units of the proper normalization.

If you want to correct input to posterfiner just please check what is the proper normalization and the values you will get will hold (approximately) for all structures computed with meridien.

**Pull request closed without merging**
