### PR TITLE
Anaconda's new compilers

### PR DESCRIPTION
**Pull request by shadowwalkersb**
This switches to use the new anaconda-provided compilers instead of the system compilers. Using the same compilers that were used to build the whole anaconda ecosystem, hopefully, will alleviate the need to maintain two Linux builds. The new compilers, also, promise to be faster and safer.

There were necessary changes to the codebase to make our builds work with the compilers.

Submitting this PR for review and discussion.

### CODE REVIEW

**Comment by shadowwalkersb** [comment]
Should add that this also upgrades to C++14.

**Comment by shadowwalkersb** [comment]
This is ready to merge. Any comments @sludtke42 ?

**Comment by sludtke42** [comment]
This is linux only?  What g++ version does anaconda use?

--------------------------------------------------------------------------------------
Steven Ludtke, Ph.D. <sludtke@bcm.edu <mailto:sludtke@bcm.edu>>                      Baylor College of Medicine 
Charles C. Bell Jr., Professor of Structural Biology
Dept. of Biochemistry and Molecular Biology                      (www.bcm.edu/biochem <http://www.bcm.edu/biochem>)
Academic Director, CryoEM Core                                        (cryoem.bcm.edu <http://cryoem.bcm.edu/>)
Co-Director CIBR Center                                    (www.bcm.edu/research/cibr <http://www.bcm.edu/research/cibr>)
Co-Director National Center For Macromolecular Imaging                  (ncmi.bcm.edu <http://ncmi.bcm.edu/>)

**Comment by shadowwalkersb** [comment]
These are from build logs as cmake identifies the compilers.
```
-- The CXX compiler identification is GNU 7.2.0      # Linux
-- The CXX compiler identification is Clang 4.0.1    # Mac
```

**Pull request merged**
