### PR TITLE
Install python modules into site-packages

### PR DESCRIPTION
**Pull request by shadowwalkersb**
- Introduces new cmake variable: `EMAN_PY_INSTALL_PREFIX`.
- Updates installation locations for conda- and non-conda-builds w.r.t. `EMAN_PY_INSTALL_PREFIX`, only the locations that are not referenced in the code via hard-coded paths relative to `EMAN2DIR`. Hard-coded locations are 
  ```
  EMAN2DIR/bin
  EMAN2DIR/images
  EMAN2DIR/fonts
  EMAN2DIR/lib/pmconfig
  ```
- Updates tests.

---

The purpose of these changes is so that python can find eman libraries woithout the need to set `PYTHONPATH`.

### CODE REVIEW

**Comment by jamesmbell** [comment]
Does this get rid of the EMAN2DIR environment variable? If so, we may need to modify a few python files. Some programs reference this variable, but I really think it'd be better if users didn't need to define environment variables beyond adding EMAN2 to their PATH.

Running a grep for EMAN2DIR in the relevant parts of the source tree, I find: 

`./libpyEM/EMAN2.py:		url=os.getenv("EMAN2DIR")
./libpyEM/EMAN2.py:		url=os.getenv("EMAN2DIR")
./libpyEM/EMAN2.py:		return os.getenv("EMAN2DIR")+ dtag + "images" + dtag + "macimages" + dtag
./libpyEM/EMAN2.py:		return os.getenv("EMAN2DIR")+ dtag + "images" + dtag
./libpyEM/EMAN2.py:			font_renderer.set_font_file_name(os.getenv("EMAN2DIR")+"/fonts/DejaVuSerif.ttf")
./libpyEM/EMAN2PAR.py:					proc=subprocess.Popen(["python", "%s\\bin\\e2parallel.py"%os.getenv('EMAN2DIR'),"localclient","--taskin=%s/%07d"%(self.scratchdir,self.nextid),"--taskout=%s/%07d.out"%(self.scratchdir,self.nextid)])
./libpyEM/qtgui/emsprworkflow.py:		self.form.setWindowIcon(QtGui.QIcon(os.getenv("EMAN2DIR")+"/images/feather.png"))
./programs/CMakeLists.txt:# SET(E2D $ENV{EMAN2DIR})
./programs/e2.py:e2real=os.getenv("EMAN2DIR")+"/bin/e2_real.py"
./programs/e2history.py:		self.form.setWindowIcon(QtGui.QIcon(os.getenv("EMAN2DIR")+"/images/feather.png"))
./programs/e2projectmanager.py:		self.pm_icon = self.pm_icon_default = os.getenv("EMAN2DIR")+"/images/EMAN2Icon.png"
./programs/e2projectmanager.py:		EMAN2DIR = os.getenv("EMAN2DIR")
./programs/e2projectmanager.py:		jsonfile = open(os.getenv("EMAN2DIR")+'/lib/pmconfig/icons.json', 'r')
./programs/e2projectmanager.py:			self.icons[icon] = QtGui.QIcon(EMAN2DIR+icons[icon])
./programs/e2projectmanager.py:		self.tree_stacked_widget.addWidget(self.makeTreeWidget(os.getenv("EMAN2DIR")+'/lib/pmconfig/spr.json', 'SPR'))
./programs/e2projectmanager.py:		#self.tree_stacked_widget.addWidget(self.makeTreeWidget(os.getenv("EMAN2DIR")+'/lib/pmconfig/spt.json', 'SPT'))
./programs/e2projectmanager.py:		self.tree_stacked_widget.addWidget(self.makeTreeWidget(os.getenv("EMAN2DIR")+'/lib/pmconfig/tomo.json', 'Tomography'))
./programs/e2projectmanager.py:			self.tree_stacked_widget.addWidget(self.makeTreeWidget(os.getenv("EMAN2DIR")+'/lib/pmconfig/tomosegpanel.json', 'TomogramSegmentation'))
./programs/e2projectmanager.py:		jsonfile = open(os.getenv("EMAN2DIR")+self.getProgramWizardFile(), 'r')
./programs/e2projectmanager.py:			f = open(os.getenv("EMAN2DIR")+"/bin/"+program,"r")
./programs/e2projectmanager.py:			f = open(os.getenv("EMAN2DIR")+"/bin/"+e2program,"r")
./programs/e2projectmanager.py:		hbox.addWidget(PMIcon(os.getenv("EMAN2DIR")+"/images/SirEMAN2.png"))
./sparx/bin/sx.py:e2real=os.getenv("EMAN2DIR")+"/bin/sx_real.py"
./sparx/bin/sxgui.py:			self.qsub_script_edit.setToolTip('<FONT>'+"File name of submission script template (e.g. $EMAN2DIR/bin/msgui_qsub.sh)"+'</FONT>')
./sparx/templates/sxgui_template.py:			self.qsub_script_edit.setToolTip('<FONT>'+"File name of submission script template (e.g. $EMAN2DIR/bin/msgui_qsub.sh)"+'</FONT>')`

**Comment by shadowwalkersb** [comment]
I tried to be clear in the description and the commits, but if it is not as clear as I thought, we should discuss in person.

**Comment by shadowwalkersb** [comment]
Please, see the updated description.

**Comment by shadowwalkersb** [comment]
> Running a grep for EMAN2DIR in the relevant parts of the source tree, I find:

This should be addressed in a separate issue or PR. This PR may be helpful in going that direction, but is meant to address only the `PYTHONPATH` issue. So, if there are no objections to this PR, can we merge it or close it?

**Comment by shadowwalkersb** [comment]
> Nonetheless, I really think it'd be better if users didn't need to define environment variables beyond adding EMAN2 to their PATH.

@jamesmbell , see this comment, https://github.com/cryoem/eman2/pull/20#issuecomment-284921254 and the corresponding PR.

**Comment by sludtke42** [comment]
It would probably be pretty straightforward to modify EMAN2.py so it generates EMAN2DIR from argv[0], however that would break if someone were writing their own script, for example in the current directory (which is still in their PATH). I wouldn't object to having "from EMAN2 import *" set EMAN2DIR automatically if it isn't already set in the user's environment.

----------------------------------------------------------------------------
Steven Ludtke, Ph.D.
Professor, Dept. of Biochemistry and Mol. Biol.                Those who do
Co-Director National Center For Macromolecular Imaging	           ARE
Baylor College of Medicine                                     The converse
sludtke@bcm.edu  -or-  stevel@alumni.caltech.edu               also applies
http://ncmi.bcm.edu/~stevel

**Comment by shadowwalkersb** [comment]
> It would probably be pretty straightforward to modify EMAN2.py so it generates EMAN2DIR from argv[0], however that would break if someone were writing their own script, for example in the current directory (which is still in their PATH). I wouldn't object to having "from EMAN2 import *" set EMAN2DIR automatically if it isn't already set in the user's environment.

In that PR `EMAN2DIR` was set in `EMAN2.py` and not using `argv[0]`, but relative to `EMAN2.py`'s location which is fixed (see https://github.com/cryoem/eman2/pull/20/commits/a561b573ec06b976f9c692a8c4ae24e2a3404442#diff-59f97c44001d9e259ab53f756c1be74aR65) unlike `argv[0]`. Specifically, we add this line to EMAN2.py: `os.environ["EMAN2DIR"] = os.path.join(os.path.dirname(__file__), os.pardir)`.

@jamesmbell and I figure that this is a more general solution. Do you agree?

**Comment by sludtke42** [comment]
Fine, but don't override a user-set variable.
----------------------------------------------------------------------------
Steven Ludtke, Ph.D.
Professor, Dept. of Biochemistry and Mol. Biol.                Those who do
Co-Director National Center For Macromolecular Imaging	           ARE
Baylor College of Medicine                                     The converse
sludtke@bcm.edu  -or-  stevel@alumni.caltech.edu               also applies
http://ncmi.bcm.edu/~stevel

**Pull request merged**
