### PR TITLE
Cleanup files

### PR DESCRIPTION
**Pull request by shadowwalkersb**

### CODE REVIEW

**Comment by shadowwalkersb** [comment]
Here is a table of my reasoning with corresponding reviewers... When reviewing, take a look at the list of changed files in case I forgot to list any in the table.

| File(s) | Explanation | Reviewer |
|-------|-------------|----------|
|**sparx/libpy/__init__.py** | Currently, all sparx/libpy/*.py files are installed into `site-packages`. When `__init__.py` exists in a folder, it becomes a Python package. So, with this file, the whole `site-packages` folder becomes a Python package. Not a good idea, although it has not caused any apparent problems. | @pawelpap9 and SPARX/SPHIRE devs. |
|**libEM/emdata_gl.cpp**, **libEM/emdata_gl.h** | All code is commented-out. | |
| **libEM/pmconfig/raw** | Seems incomplete when compared with `libEM/pmconfig/rawdata.json`. | @sludtke42 |
| **libpyEM/sparxutil.pyste** | Probably obsolete. | @pawelpap9 and SPARX/SPHIRE devs. |
| **libpyEM/sparx.cpp**, **libpyEM/sparx.h** | These contain only two functions. Are they used? `em2flex()` and `flex2em()` | @pawelpap9 and SPARX/SPHIRE devs. |
| **libpyEM/pyexception.cpp**, **libpyEM/pyexception.h** | These contain only one function. Is it used? `translate1()` | @sludtke42 |
| **pyemtbx/files.py** | Contains one function. I can't find any calls to it. `def remove_files(pattern, absdir=None)` | @sludtke42 |
| **INSTALL** | Not relevant anymore?  | @sludtke42 |
| **README** | Updated, needs review.  | @sludtke42 |

**Comment by sludtke42** [comment]
ok

**Comment by shadowwalkersb** [comment]
@sludtke42 , @pawelpap9 , any objections from the reviewers listed in the table above?

**Comment by pawelpap9** [comment]
I can look into it on Monday. Our buffer machine is still down. 

Regards,
Pawel

**Comment by pawelpap9** [comment]
| File(s)
 | Explanation | Reviewer |
| sparx/libpy/init.py









NO IDEA WHAT THAT IS.



 | Currently, all sparx/libpy/*.py files are installed into site-packages. When __init__.py exists in a folder, it becomes a Python package. So, with this file, the whole site-packages folder becomes a Python package. Not a good idea, although it has not caused any apparent problems. | @pawelpap9 and SPARX/SPHIRE devs.
 |
| libEM/emdata_gl.cpp, libEM/emdata_gl.h | All code is commented-out. |  |
| libEM/pmconfig/raw | Seems incomplete when compared with libEM/pmconfig/rawdata.json. | @sludtke42 |
| libpyEM/sparxutil.pysteNO IDEA WHAT THAT IS. | Probably obsolete. | @pawelpap9 and SPARX/SPHIRE devs. |
| libpyEM/sparx.cpp, libpyEM/sparx.h

THEY ARE NO USED ANYWHERE BUT IT APPEARS TO BE VALID CODE.  IF you may please move the code to libEM/sparx/emdata_sparx
I could also move them | These contain only two functions. Are they used? em2flex() and flex2em() | @pawelpap9 and SPARX/SPHIRE devs. |
| libpyEM/pyexception.cpp, libpyEM/pyexception.h | These contain only one function. Is it used? translate1() | @sludtke42 |
| pyemtbx/files.py | Contains one function. I can't find any calls to it. def remove_files(pattern, absdir=None) | @sludtke42 |
| INSTALL | Not relevant anymore? | @sludtke42 |
| README | Updated, needs review. | @sludtke42 |

**Comment by shadowwalkersb** [comment]
@pawelpap9 , I brought back sparx.cpp and sparx.h. The message was garbled, but as far as I can tell, these are the only files that you wanted to keep, right?

@sludtke42 , can you take another look at the table, https://github.com/cryoem/eman2/pull/123#issuecomment-334043288? Also, there was another file removed in https://github.com/cryoem/eman2/pull/123/commits/6a5ebb8fbb334f3263e4bd06080d985fa96acb7d.

**Pull request merged**
