### PR TITLE
Attempt to fix e2filtertool crashes

### PR DESCRIPTION
**Pull request by shadowwalkersb**

### CODE REVIEW

**Comment by shadowwalkersb** [comment]
With a stack passed to e2filtertool, I don't seem to be able to pop FFT buttons, anyway. If I pass two files, here is what I get.

```
$ e2filtertool.py test_eman/twod.hdf test_eman/twod2.png
usage: prog [options] <image file>

	Provides a GUI interface for applying a sequence of processors to an image, stack of images or a volume.
e2filtertool.py: error: You must specify a single data file on the command-line.
```

So, I don't get the GUI with FFT, phase and amp buttons, anyway. Additionally, here is a screenshot which displays all the images, with the change in this PR.
screen shot 2017-08-08 at 1 46 04 pm

**Comment by sludtke42** [comment]
This is about the generic widget, not just e2filtertool. If you run e2filtertool with a stack of images, it will open a tiled display widget by default. There is an option on the view menu which will open a single-image display widget, which has the FFT controls. The code you're editing (emimage2d.py) is used throughout the system, not just in e2filtertool.

----------------------------------------------------------------------------
Steven Ludtke, Ph.D.
Professor, Dept of Biochemistry and Mol. Biol.         (www.bcm.edu/biochem)
Co-Director National Center For Macromolecular Imaging        (ncmi.bcm.edu)
Co-Director CIBR Center                          (www.bcm.edu/research/cibr)
Baylor College of Medicine                             
sludtke@bcm.edu

**Comment by shadowwalkersb** [comment]
OK, I have tried a stack with more than one image and everything works. The crashes reported occur when a single image is opened. I believe you can reproduce the crashes if you use a snapshot from before your two patches when you give e2filtertool a single image.

**Comment by shadowwalkersb** [comment]
FFT buttons seem to work when e2display is used to open a single image. So, I don't think the general system has a problem, it is just e2filtertool.

**Comment by shadowwalkersb** [comment]
`e2filtertool.py single_im.hdf`

screen shot 2017-08-09 at 12 17 25 am

---

`e2filtertool.py stack2.hdf`

screen shot 2017-08-09 at 12 19 00 am
screen shot 2017-08-09 at 12 19 31 am

**Comment by shadowwalkersb** [comment]
> So, my previous comment for the change at line 591 still holds. If there are multiple images in the test set, it seems like this will cause only the first image in the stack to be displayed.

See screenshots in https://github.com/cryoem/eman2/pull/117#issuecomment-321156277. It works for a single image and for a stack.

**Pull request closed without merging**
