### PR TITLE
Fix print statements

### PR DESCRIPTION
**Pull request by shadowwalkersb**

### CODE REVIEW

**Comment by g5v991x** [comment]
I am fine with the changes but why all build failed?

**Comment by shadowwalkersb** [comment]
That's because of another typo that needs to be fixed. Also, can you approve this on GitHub when you get a chance?

**Comment by shadowwalkersb** [comment]
> I am fine with the changes but why all build failed?

```
Compiling ./examples/e2ddd_external.py ...
  File "./examples/e2ddd_external.py", line 165
    if options.patch != 1 1: cmd += " -Patch {} ".format(options.patch)
                          ^
SyntaxError: invalid syntax
```

**Comment by g5v991x** [comment]
Need to ask Steve or Michael ... not sure what this does or whether it does anything now...

**Comment by shadowwalkersb** [comment]
Oh, here is where that code was introduced.
https://github.com/cryoem/eman2/blob/98bea259890d523f6815b423d45911f22d23d3b5/examples/e2ddd_external.py#L165
I was just pointing out what the reason for the failing tests were and that the failure wasn't related to the changes here. So, @jamesmbell will be the best person to fix it.

**Pull request merged**
